# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WallOfDenial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
